### PR TITLE
feat: oidc provider configuration to list

### PR DESCRIPTION
**Pull request by miyunari**
The OIDC config is now provided as a list. 

Jira: https://issues.redhat.com/browse/SECURESIGN-1164

image

### CODE REVIEW

**Comment by bkabrda** [comment]
Thanks for the PR, it looks really good. Have you tested usage of multiple issuers? If you did and it worked, I can approve.

**Comment by osmman** [comment]
Can you configure MetaIssuers by OIDC config because Fulcio has two types: OIDCIssuers and MetaIssuers?

**Comment by miyunari** [comment]
@bkabrda yes, I tested it :) 

>Can you configure MetaIssuers by OIDC config because Fulcio has two types: OIDCIssuers and MetaIssuers?
@osmman should we take care of this in an extra PR or do you think it belongs here aswell? :)

**Comment by osmman** [comment]
> > Can you configure MetaIssuers by OIDC config because Fulcio has two types: OIDCIssuers and MetaIssuers?
> 
> @osmman should we take care of this in an extra PR or do you think it belongs here aswell? :)

It can be done in extra PR, it will be good to enable users to set all Fulcio's OIDC options. you can find the definition [here ](https://github.com/securesign/fulcio/blob/main/pkg/config/config.go#L50-L88)

**Review by bkabrda — APPROVED** [review]
Approving, thanks! As Tomas noted, please open a followup PR with the additional changes.

**Pull request merged**
