### PR TITLE
[SECURESIGN-1479] Trillian TLS: add external DB TLS CA certificate

### PR DESCRIPTION
**Pull request by fghanmi**

### CODE REVIEW

**Review by SequeI — APPROVED** [review]
lgtm, nice work

**Comment by bkabrda** [comment]
This looks good, thanks! Is there a way we could extend the `user_provided` molecule scenario to test for this?

**Comment by bkabrda** [comment]
There seems to be an error in the molecule default scenario execution, can you please take a look?

```
  TASK [Setting tas_single_node_trillian_trusted_ca] *****************************
  fatal: [18.117.96.15]: FAILED! => {"msg": "The 'file' lookup had an issue accessing the file '/etc/mysql/ssl/ca-cert.pem'. file not found, use -vvvvv to see paths searched"}
```

**Review by bkabrda — APPROVED** [review]
LGTM, nice job!

**Pull request merged**
