### PR TITLE
Use tuffer to pre-initialize the TUF repository and serve it via an httpd container

### PR DESCRIPTION
**Pull request by bkabrda**
This PR makes the collection use the "tuffer" image to pre-create the TUF repository first and then use a simple httpd container to serve the repository.

Contained are workarounds for features missing in podman 4.4 (our baseline) - inability to create k8s "Job" (replaced by a simple Deployment with "restartPolicy: Never" and inability to propagate exit code of a Deployment to systemd (checking for container exit code and failing with an error message if the exit code != 0).

### CODE REVIEW

**Review by SequeI — APPROVED** [review]
LGTM, please add port and pod/service name as a variable for new TUF addition! Thanks

**Comment by SequeI** [comment]
LGTM after lint passes, thanks for taking a recent manifest with all the probes included !

**Comment by tommyd450** [comment]
Installing playbook and poking around now! I wish to look at changes within the machine im running it on.

**Comment by tommyd450** [comment]
Following up on this, started an install and oddly the httpd server isnt there, podman logs report its creation yet there is no pod/container? Running the install on an Openstack Machine.

**Comment by bkabrda** [comment]
@tommyd450 I provided an explicit unique hostPort for the TUF server, so that should fix this PR.

Context: we discovered in an offline investigation that some old podman versions, e.g. 4.4.1, automatically expose the container port as hostPort, so we must either have unique container ports (impossible in this case, the httpd container we're using hardcodes 8080) or we have to explicitly provide a unique hostPort to do which is what I did.

**Comment by tommyd450** [comment]
@bkabrda Having looked over it earlier it all looks good to me!

**Pull request merged**
